### ISSUE TITLE
lwip STABLE-1_4_1 test

### ISSUE THREAD

**Issue by cherich** [yarrick/lwip-merged#1]
hello,
I can use merged you provided to test the new lwip, but can't test lwip STABLE-1_4_1. Can you help me?
thank you!

**Comment by yarrick** [comment]
You can test any branch by just checking out the same version of both lwip and lwip-contrib in a directory next to each other. Then go into the contrib directory and build the binary you want, and run the tests.

**Comment by yarrick** [comment]
That branch no longer receives any updates so it would not make sense to follow it here.
